package co.edu.usbcali.modelo;
// Generated 21-mar-2016 1:53:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private long cliCedula;
	private String cliNombre;
	private String cliDireccion;
	private String cliTelefono;
	private Set<Mascotas> mascotases = new HashSet<Mascotas>(0);

	public Clientes() {
	}

	public Clientes(long cliCedula, String cliNombre, String cliDireccion, String cliTelefono) {
		this.cliCedula = cliCedula;
		this.cliNombre = cliNombre;
		this.cliDireccion = cliDireccion;
		this.cliTelefono = cliTelefono;
	}

	public Clientes(long cliCedula, String cliNombre, String cliDireccion, String cliTelefono,
			Set<Mascotas> mascotases) {
		this.cliCedula = cliCedula;
		this.cliNombre = cliNombre;
		this.cliDireccion = cliDireccion;
		this.cliTelefono = cliTelefono;
		this.mascotases = mascotases;
	}

	public long getCliCedula() {
		return this.cliCedula;
	}

	public void setCliCedula(long cliCedula) {
		this.cliCedula = cliCedula;
	}

	public String getCliNombre() {
		return this.cliNombre;
	}

	public void setCliNombre(String cliNombre) {
		this.cliNombre = cliNombre;
	}

	public String getCliDireccion() {
		return this.cliDireccion;
	}

	public void setCliDireccion(String cliDireccion) {
		this.cliDireccion = cliDireccion;
	}

	public String getCliTelefono() {
		return this.cliTelefono;
	}

	public void setCliTelefono(String cliTelefono) {
		this.cliTelefono = cliTelefono;
	}

	public Set<Mascotas> getMascotases() {
		return this.mascotases;
	}

	public void setMascotases(Set<Mascotas> mascotases) {
		this.mascotases = mascotases;
	}

}
