package co.edu.usbcali.modelo;
// Generated 21-mar-2016 1:53:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Mascotas generated by hbm2java
 */
public class Mascotas implements java.io.Serializable {

	private long masCodigo;
	private Clientes clientes;
	private String masNombre;
	private long masEdad;
	private Set<VacunasMascotas> vacunasMascotases = new HashSet<VacunasMascotas>(0);

	public Mascotas() {
	}

	public Mascotas(long masCodigo, Clientes clientes, String masNombre, long masEdad) {
		this.masCodigo = masCodigo;
		this.clientes = clientes;
		this.masNombre = masNombre;
		this.masEdad = masEdad;
	}

	public Mascotas(long masCodigo, Clientes clientes, String masNombre, long masEdad,
			Set<VacunasMascotas> vacunasMascotases) {
		this.masCodigo = masCodigo;
		this.clientes = clientes;
		this.masNombre = masNombre;
		this.masEdad = masEdad;
		this.vacunasMascotases = vacunasMascotases;
	}

	public long getMasCodigo() {
		return this.masCodigo;
	}

	public void setMasCodigo(long masCodigo) {
		this.masCodigo = masCodigo;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public String getMasNombre() {
		return this.masNombre;
	}

	public void setMasNombre(String masNombre) {
		this.masNombre = masNombre;
	}

	public long getMasEdad() {
		return this.masEdad;
	}

	public void setMasEdad(long masEdad) {
		this.masEdad = masEdad;
	}

	public Set<VacunasMascotas> getVacunasMascotases() {
		return this.vacunasMascotases;
	}

	public void setVacunasMascotases(Set<VacunasMascotas> vacunasMascotases) {
		this.vacunasMascotases = vacunasMascotases;
	}

}
