package co.edu.usbcali.modelo;
// Generated 21-mar-2016 1:53:18 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * VacunasMascotas generated by hbm2java
 */
public class VacunasMascotas implements java.io.Serializable {

	private VacunasMascotasId id;
	private Vacunas vacunas;
	private Mascotas mascotas;
	private Date vacmasFecha;

	public VacunasMascotas() {
	}

	public VacunasMascotas(VacunasMascotasId id, Vacunas vacunas, Mascotas mascotas, Date vacmasFecha) {
		this.id = id;
		this.vacunas = vacunas;
		this.mascotas = mascotas;
		this.vacmasFecha = vacmasFecha;
	}

	public VacunasMascotasId getId() {
		return this.id;
	}

	public void setId(VacunasMascotasId id) {
		this.id = id;
	}

	public Vacunas getVacunas() {
		return this.vacunas;
	}

	public void setVacunas(Vacunas vacunas) {
		this.vacunas = vacunas;
	}

	public Mascotas getMascotas() {
		return this.mascotas;
	}

	public void setMascotas(Mascotas mascotas) {
		this.mascotas = mascotas;
	}

	public Date getVacmasFecha() {
		return this.vacmasFecha;
	}

	public void setVacmasFecha(Date vacmasFecha) {
		this.vacmasFecha = vacmasFecha;
	}

}
