package co.edu.usbcali.modelo;
// Generated 21-mar-2016 1:53:18 by Hibernate Tools 4.0.0

/**
 * VacunasMascotasId generated by hbm2java
 */
public class VacunasMascotasId implements java.io.Serializable {

	private long masCodigo;
	private long vacCodigo;

	public VacunasMascotasId() {
	}

	public VacunasMascotasId(long masCodigo, long vacCodigo) {
		this.masCodigo = masCodigo;
		this.vacCodigo = vacCodigo;
	}

	public long getMasCodigo() {
		return this.masCodigo;
	}

	public void setMasCodigo(long masCodigo) {
		this.masCodigo = masCodigo;
	}

	public long getVacCodigo() {
		return this.vacCodigo;
	}

	public void setVacCodigo(long vacCodigo) {
		this.vacCodigo = vacCodigo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VacunasMascotasId))
			return false;
		VacunasMascotasId castOther = (VacunasMascotasId) other;

		return (this.getMasCodigo() == castOther.getMasCodigo()) && (this.getVacCodigo() == castOther.getVacCodigo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMasCodigo();
		result = 37 * result + (int) this.getVacCodigo();
		return result;
	}

}
